version: '3.1'
services:
  fulcio-server-debug:
    build:
      context: .
      target: "debug"
    command: [
      "dlv",
      "exec",
      "--listen=:2345",
      "--headless=true",
      "--log=true",
      "--api-version=2",
      "--",
      "/usr/local/bin/fulcio-server",
      "serve",
      "--host=0.0.0.0",
      "--port=3000",
      ]
    restart: always # keep the server running
    ports:
      - "3000:3000"
      - "2345:2345"
      - "2112:2112"
